const COUNTRY_NAMES = {
  BR: { pt: 'Brasil', en: 'Brazil' },
  PT: { pt: 'Portugal', en: 'Portugal' },
  US: { pt: 'Estados Unidos', en: 'United States' },
  AR: { pt: 'Argentina', en: 'Argentina' },
  ES: { pt: 'Espanha', en: 'Spain' },
  FR: { pt: 'França', en: 'France' },
  DE: { pt: 'Alemanha', en: 'Germany' },
  IT: { pt: 'Itália', en: 'Italy' },
  GB: { pt: 'Reino Unido', en: 'United Kingdom' },
  CA: { pt: 'Canadá', en: 'Canada' },
  MX: { pt: 'México', en: 'Mexico' },
  CL: { pt: 'Chile', en: 'Chile' },
  CO: { pt: 'Colômbia', en: 'Colombia' },
  PE: { pt: 'Peru', en: 'Peru' },
  UY: { pt: 'Uruguai', en: 'Uruguay' },
  PY: { pt: 'Paraguai', en: 'Paraguay' },
  BO: { pt: 'Bolívia', en: 'Bolivia' },
  VE: { pt: 'Venezuela', en: 'Venezuela' },
  EC: { pt: 'Equador', en: 'Ecuador' },
  JP: { pt: 'Japão', en: 'Japan' },
  CN: { pt: 'China', en: 'China' },
  KR: { pt: 'Coreia do Sul', en: 'South Korea' },
  IN: { pt: 'Índia', en: 'India' },
  AU: { pt: 'Austrália', en: 'Australia' },
  RU: { pt: 'Rússia', en: 'Russia' },
  NL: { pt: 'Países Baixos', en: 'Netherlands' },
  BE: { pt: 'Bélgica', en: 'Belgium' },
  CH: { pt: 'Suíça', en: 'Switzerland' },
  AT: { pt: 'Áustria', en: 'Austria' },
  SE: { pt: 'Suécia', en: 'Sweden' },
  NO: { pt: 'Noruega', en: 'Norway' },
  DK: { pt: 'Dinamarca', en: 'Denmark' },
  FI: { pt: 'Finlândia', en: 'Finland' },
  IE: { pt: 'Irlanda', en: 'Ireland' },
  PL: { pt: 'Polônia', en: 'Poland' },
  CZ: { pt: 'Tchéquia', en: 'Czech Republic' },
  HU: { pt: 'Hungria', en: 'Hungary' },
  GR: { pt: 'Grécia', en: 'Greece' },
  TR: { pt: 'Turquia', en: 'Turkey' },
  ZA: { pt: 'África do Sul', en: 'South Africa' },
  EG: { pt: 'Egito', en: 'Egypt' },
  MA: { pt: 'Marrocos', en: 'Morocco' },
  NG: { pt: 'Nigéria', en: 'Nigeria' },
  KE: { pt: 'Quênia', en: 'Kenya' },
  AO: { pt: 'Angola', en: 'Angola' },
  MZ: { pt: 'Moçambique', en: 'Mozambique' },
  CV: { pt: 'Cabo Verde', en: 'Cape Verde' },
  SA: { pt: 'Arábia Saudita', en: 'Saudi Arabia' },
  AE: { pt: 'Emirados Árabes Unidos', en: 'United Arab Emirates' },
  IL: { pt: 'Israel', en: 'Israel' },
  TH: { pt: 'Tailândia', en: 'Thailand' },
  VN: { pt: 'Vietnã', en: 'Vietnam' },
  ID: { pt: 'Indonésia', en: 'Indonesia' },
  PH: { pt: 'Filipinas', en: 'Philippines' },
  MY: { pt: 'Malásia', en: 'Malaysia' },
  SG: { pt: 'Singapura', en: 'Singapore' },
  NZ: { pt: 'Nova Zelândia', en: 'New Zealand' },
  UA: { pt: 'Ucrânia', en: 'Ukraine' },
  RO: { pt: 'Romênia', en: 'Romania' },
  BG: { pt: 'Bulgária', en: 'Bulgaria' },
  HR: { pt: 'Croácia', en: 'Croatia' },
  SK: { pt: 'Eslováquia', en: 'Slovakia' },
  SI: { pt: 'Eslovênia', en: 'Slovenia' },
  RS: { pt: 'Sérvia', en: 'Serbia' },
  CR: { pt: 'Costa Rica', en: 'Costa Rica' },
  PA: { pt: 'Panamá', en: 'Panama' },
  DO: { pt: 'República Dominicana', en: 'Dominican Republic' },
  PR: { pt: 'Porto Rico', en: 'Puerto Rico' },
  GT: { pt: 'Guatemala', en: 'Guatemala' },
  HN: { pt: 'Honduras', en: 'Honduras' },
  SV: { pt: 'El Salvador', en: 'El Salvador' },
  NI: { pt: 'Nicarágua', en: 'Nicaragua' },
  CU: { pt: 'Cuba', en: 'Cuba' },
  JM: { pt: 'Jamaica', en: 'Jamaica' },
  DZ: { pt: 'Argélia', en: 'Algeria' },
  TN: { pt: 'Tunísia', en: 'Tunisia' },
  GH: { pt: 'Gana', en: 'Ghana' },
  PK: { pt: 'Paquistão', en: 'Pakistan' },
  BD: { pt: 'Bangladesh', en: 'Bangladesh' },
  LK: { pt: 'Sri Lanka', en: 'Sri Lanka' },
  NP: { pt: 'Nepal', en: 'Nepal' },
  KZ: { pt: 'Cazaquistão', en: 'Kazakhstan' },
  UZ: { pt: 'Uzbequistão', en: 'Uzbekistan' },
  QA: { pt: 'Catar', en: 'Qatar' },
  KW: { pt: 'Kuweit', en: 'Kuwait' },
  OM: { pt: 'Omã', en: 'Oman' },
  BH: { pt: 'Bahrein', en: 'Bahrain' },
  JO: { pt: 'Jordânia', en: 'Jordan' },
  LB: { pt: 'Líbano', en: 'Lebanon' },
  IS: { pt: 'Islândia', en: 'Iceland' },
  LU: { pt: 'Luxemburgo', en: 'Luxembourg' },
  MT: { pt: 'Malta', en: 'Malta' },
  CY: { pt: 'Chipre', en: 'Cyprus' },
  EE: { pt: 'Estônia', en: 'Estonia' },
  LV: { pt: 'Letônia', en: 'Latvia' },
  LT: { pt: 'Lituânia', en: 'Lithuania' },
  GE: { pt: 'Geórgia', en: 'Georgia' },
  AM: { pt: 'Armênia', en: 'Armenia' },
  AZ: { pt: 'Azerbaijão', en: 'Azerbaijan' },
  AL: { pt: 'Albânia', en: 'Albania' },
  MK: { pt: 'Macedônia do Norte', en: 'North Macedonia' },
  BA: { pt: 'Bósnia e Herzegovina', en: 'Bosnia and Herzegovina' },
  ME: { pt: 'Montenegro', en: 'Montenegro' },
  TW: { pt: 'Taiwan', en: 'Taiwan' },
  HK: { pt: 'Hong Kong', en: 'Hong Kong' },
  MO: { pt: 'Macau', en: 'Macau' },
  MN: { pt: 'Mongólia', en: 'Mongolia' },
  KH: { pt: 'Camboja', en: 'Cambodia' },
  LA: { pt: 'Laos', en: 'Laos' },
  MM: { pt: 'Mianmar', en: 'Myanmar' },
  SN: { pt: 'Senegal', en: 'Senegal' },
  CI: { pt: 'Costa do Marfim', en: 'Ivory Coast' },
  CM: { pt: 'Camarões', en: 'Cameroon' },
  ET: { pt: 'Etiópia', en: 'Ethiopia' },
  TZ: { pt: 'Tanzânia', en: 'Tanzania' },
  UG: { pt: 'Uganda', en: 'Uganda' },
  ZW: { pt: 'Zimbábue', en: 'Zimbabwe' },
  NA: { pt: 'Namíbia', en: 'Namibia' },
  BW: { pt: 'Botsuana', en: 'Botswana' }
};

export const COUNTRIES = Object.entries(COUNTRY_NAMES).map(([code, names]) => ({
  code,
  name: names.pt,
  nameEn: names.en,
  flag: getFlag(code)
}));

function getFlag(code) {
  const flags = {
    BR:'🇧🇷',PT:'🇵🇹',US:'🇺🇸',AR:'🇦🇷',ES:'🇪🇸',FR:'🇫🇷',DE:'🇩🇪',IT:'🇮🇹',GB:'🇬🇧',CA:'🇨🇦',
    MX:'🇲🇽',CL:'🇨🇱',CO:'🇨🇴',PE:'🇵🇪',UY:'🇺🇾',PY:'🇵🇾',BO:'🇧🇴',VE:'🇻🇪',EC:'🇪🇨',JP:'🇯🇵',
    CN:'🇨🇳',KR:'🇰🇷',IN:'🇮🇳',AU:'🇦🇺',RU:'🇷🇺',NL:'🇳🇱',BE:'🇧🇪',CH:'🇨🇭',AT:'🇦🇹',SE:'🇸🇪',
    NO:'🇳🇴',DK:'🇩🇰',FI:'🇫🇮',IE:'🇮🇪',PL:'🇵🇱',CZ:'🇨🇿',HU:'🇭🇺',GR:'🇬🇷',TR:'🇹🇷',ZA:'🇿🇦',
    EG:'🇪🇬',MA:'🇲🇦',NG:'🇳🇬',KE:'🇰🇪',AO:'🇦🇴',MZ:'🇲🇿',CV:'🇨🇻',SA:'🇸🇦',AE:'🇦🇪',IL:'🇮🇱',
    TH:'🇹🇭',VN:'🇻🇳',ID:'🇮🇩',PH:'🇵🇭',MY:'🇲🇾',SG:'🇸🇬',NZ:'🇳🇿',UA:'🇺🇦',RO:'🇷🇴',BG:'🇧🇬',
    HR:'🇭🇷',SK:'🇸🇰',SI:'🇸🇮',RS:'🇷🇸',CR:'🇨🇷',PA:'🇵🇦',DO:'🇩🇴',PR:'🇵🇷',GT:'🇬🇹',HN:'🇭🇳',
    SV:'🇸🇻',NI:'🇳🇮',CU:'🇨🇺',JM:'🇯🇲',DZ:'🇩🇿',TN:'🇹🇳',GH:'🇬🇭',PK:'🇵🇰',BD:'🇧🇩',LKR:'🇱🇰',
    NP:'🇳🇵',KZ:'🇰🇿',UZ:'🇺🇿',QA:'🇶🇦',KW:'🇰🇼',OM:'🇴🇲',BH:'🇧🇭',JO:'🇯🇴',LB:'🇱🇧',IS:'🇮🇸',
    LU:'🇱🇺',MT:'🇲🇹',CY:'🇨🇾',EE:'🇪🇪',LV:'🇱🇻',LT:'🇱🇹',GE:'🇬🇪',AM:'🇦🇲',AZ:'🇦🇿',AL:'🇦🇱',
    MK:'🇲🇰',BA:'🇧🇦',ME:'🇲🇪',TW:'🇹🇼',HK:'🇭🇰',MO:'🇲🇴',MN:'🇲🇳',KH:'🇰🇭',LA:'🇱🇦',MM:'🇲🇲',
    SN:'🇸🇳',CI:'🇨🇮',CM:'🇨🇲',ET:'🇪🇹',TZ:'🇹🇿',UG:'🇺🇬',ZW:'🇿🇼',NA:'🇳🇦',BW:'🇧🇼'
  };
  return flags[code] || '🏳️';
}

export function getCountryName(code, lang = 'pt') {
  if (!code || code === 'any') return lang === 'en' ? 'Any Country' : 'Qualquer País';
  const found = COUNTRIES.find(c => c.code.toUpperCase() === String(code).toUpperCase());
  if (!found) return code;
  if (lang === 'en') return found.nameEn || found.name;
  return found.name;
}

