export const COUNTRIES = [
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'ES', name: 'Espanha', flag: '🇪🇸' },
  { code: 'FR', name: 'França', flag: '🇫🇷' },
  { code: 'DE', name: 'Alemanha', flag: '🇩🇪' },
  { code: 'IT', name: 'Itália', flag: '🇮🇹' },
  { code: 'GB', name: 'Reino Unido', flag: '🇬🇧' },
  { code: 'CA', name: 'Canadá', flag: '🇨🇦' },
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'Colômbia', flag: '🇨🇴' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'UY', name: 'Uruguai', flag: '🇺🇾' },
  { code: 'PY', name: 'Paraguai', flag: '🇵🇾' },
  { code: 'BO', name: 'Bolívia', flag: '🇧🇴' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'EC', name: 'Equador', flag: '🇪🇨' },
  { code: 'JP', name: 'Japão', flag: '🇯🇵' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'KR', name: 'Coreia do Sul', flag: '🇰🇷' },
  { code: 'IN', name: 'Índia', flag: '🇮🇳' },
  { code: 'AU', name: 'Austrália', flag: '🇦🇺' },
  { code: 'RU', name: 'Rússia', flag: '🇷🇺' },
  { code: 'NL', name: 'Países Baixos', flag: '🇳🇱' },
  { code: 'BE', name: 'Bélgica', flag: '🇧🇪' },
  { code: 'CH', name: 'Suíça', flag: '🇨🇭' },
  { code: 'AT', name: 'Áustria', flag: '🇦🇹' },
  { code: 'SE', name: 'Suécia', flag: '🇸🇪' },
  { code: 'NO', name: 'Noruega', flag: '🇳🇴' },
  { code: 'DK', name: 'Dinamarca', flag: '🇩🇰' },
  { code: 'FI', name: 'Finlândia', flag: '🇫🇮' },
  { code: 'IE', name: 'Irlanda', flag: '🇮🇪' },
  { code: 'PL', name: 'Polônia', flag: '🇵🇱' },
  { code: 'CZ', name: 'Tchéquia', flag: '🇨🇿' },
  { code: 'HU', name: 'Hungria', flag: '🇭🇺' },
  { code: 'GR', name: 'Grécia', flag: '🇬🇷' },
  { code: 'TR', name: 'Turquia', flag: '🇹🇷' },
  { code: 'ZA', name: 'África do Sul', flag: '🇿🇦' },
  { code: 'EG', name: 'Egito', flag: '🇪🇬' },
  { code: 'MA', name: 'Marrocos', flag: '🇲🇦' },
  { code: 'NG', name: 'Nigéria', flag: '🇳🇬' },
  { code: 'KE', name: 'Quênia', flag: '🇰🇪' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'MZ', name: 'Moçambique', flag: '🇲🇿' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'SA', name: 'Arábia Saudita', flag: '🇸🇦' },
  { code: 'AE', name: 'Emirados Árabes Unidos', flag: '🇦🇪' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'TH', name: 'Tailândia', flag: '🇹🇭' },
  { code: 'VN', name: 'Vietnã', flag: '🇻🇳' },
  { code: 'ID', name: 'Indonésia', flag: '🇮🇩' },
  { code: 'PH', name: 'Filipinas', flag: '🇵🇭' },
  { code: 'MY', name: 'Malásia', flag: '🇲🇾' },
  { code: 'SG', name: 'Singapura', flag: '🇸🇬' },
  { code: 'NZ', name: 'Nova Zelândia', flag: '🇳🇿' },
  { code: 'UA', name: 'Ucrânia', flag: '🇺🇦' },
  { code: 'RO', name: 'Romênia', flag: '🇷🇴' },
  { code: 'BG', name: 'Bulgária', flag: '🇧🇬' },
  { code: 'HR', name: 'Croácia', flag: '🇭🇷' },
  { code: 'SK', name: 'Eslováquia', flag: '🇸🇰' },
  { code: 'SI', name: 'Eslovênia', flag: '🇸🇮' },
  { code: 'RS', name: 'Sérvia', flag: '🇷🇸' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
  { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'PR', name: 'Porto Rico', flag: '🇵🇷' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'NI', name: 'Nicarágua', flag: '🇳🇮' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'DZ', name: 'Argélia', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunísia', flag: '🇹🇳' },
  { code: 'GH', name: 'Gana', flag: '🇬🇭' },
  { code: 'PK', name: 'Paquistão', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'LKR', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'KZ', name: 'Cazaquistão', flag: '🇰🇿' },
  { code: 'UZ', name: 'Uzbequistão', flag: '🇺🇿' },
  { code: 'QA', name: 'Catar', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuweit', flag: '🇰🇼' },
  { code: 'OM', name: 'Omã', flag: '🇴🇲' },
  { code: 'BH', name: 'Bahrein', flag: '🇧🇭' },
  { code: 'JO', name: 'Jordânia', flag: '🇯🇴' },
  { code: 'LB', name: 'Líbano', flag: '🇱🇧' },
  { code: 'IS', name: 'Islândia', flag: '🇮🇸' },
  { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'CY', name: 'Chipre', flag: '🇨🇾' },
  { code: 'EE', name: 'Estônia', flag: '🇪🇪' },
  { code: 'LV', name: 'Letônia', flag: '🇱🇻' },
  { code: 'LT', name: 'Lituânia', flag: '🇱🇹' },
  { code: 'GE', name: 'Geórgia', flag: '🇬🇪' },
  { code: 'AM', name: 'Armênia', flag: '🇦🇲' },
  { code: 'AZ', name: 'Azerbaijão', flag: '🇦🇿' },
  { code: 'AL', name: 'Albânia', flag: '🇦🇱' },
  { code: 'MK', name: 'Macedônia do Norte', flag: '🇲🇰' },
  { code: 'BA', name: 'Bósnia e Herzegovina', flag: '🇧🇦' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴' },
  { code: 'MN', name: 'Mongólia', flag: '🇲🇳' },
  { code: 'KH', name: 'Camboja', flag: '🇰🇭' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'MM', name: 'Mianmar', flag: '🇲🇲' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'CI', name: 'Costa do Marfim', flag: '🇨🇮' },
  { code: 'CM', name: 'Camarões', flag: '🇨🇲' },
  { code: 'ET', name: 'Etiópia', flag: '🇪🇹' },
  { code: 'TZ', name: 'Tanzânia', flag: '🇹🇿' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'ZW', name: 'Zimbábue', flag: '🇿🇼' },
  { code: 'NA', name: 'Namíbia', flag: '🇳🇦' },
  { code: 'BW', name: 'Botsuana', flag: '🇧🇼' }
];

export function getCountryName(code) {
  if (!code || code === 'any') return 'Qualquer País';
  const found = COUNTRIES.find(c => c.code.toUpperCase() === String(code).toUpperCase());
  return found ? `${found.flag} ${found.name}` : code;
}
