const COUNTRY_NAMES = {
  AF: { pt: 'Afeganistão', en: 'Afghanistan' },
  AL: { pt: 'Albânia', en: 'Albania' },
  DZ: { pt: 'Argélia', en: 'Algeria' },
  AD: { pt: 'Andorra', en: 'Andorra' },
  AO: { pt: 'Angola', en: 'Angola' },
  AG: { pt: 'Antígua e Barbuda', en: 'Antigua and Barbuda' },
  AR: { pt: 'Argentina', en: 'Argentina' },
  AM: { pt: 'Armênia', en: 'Armenia' },
  AU: { pt: 'Austrália', en: 'Australia' },
  AT: { pt: 'Áustria', en: 'Austria' },
  AZ: { pt: 'Azerbaijão', en: 'Azerbaijan' },
  BS: { pt: 'Bahamas', en: 'Bahamas' },
  BH: { pt: 'Bahrein', en: 'Bahrain' },
  BD: { pt: 'Bangladesh', en: 'Bangladesh' },
  BB: { pt: 'Barbados', en: 'Barbados' },
  BY: { pt: 'Bielorrússia', en: 'Belarus' },
  BE: { pt: 'Bélgica', en: 'Belgium' },
  BZ: { pt: 'Belize', en: 'Belize' },
  BJ: { pt: 'Benin', en: 'Benin' },
  BT: { pt: 'Butão', en: 'Bhutan' },
  BO: { pt: 'Bolívia', en: 'Bolivia' },
  BA: { pt: 'Bósnia e Herzegovina', en: 'Bosnia and Herzegovina' },
  BW: { pt: 'Botsuana', en: 'Botswana' },
  BR: { pt: 'Brasil', en: 'Brazil' },
  BN: { pt: 'Brunei', en: 'Brunei' },
  BG: { pt: 'Bulgária', en: 'Bulgaria' },
  BF: { pt: 'Burquina Faso', en: 'Burkina Faso' },
  BI: { pt: 'Burundi', en: 'Burundi' },
  CV: { pt: 'Cabo Verde', en: 'Cape Verde' },
  KH: { pt: 'Camboja', en: 'Cambodia' },
  CM: { pt: 'Camarões', en: 'Cameroon' },
  CA: { pt: 'Canadá', en: 'Canada' },
  CF: { pt: 'República Centro-Africana', en: 'Central African Republic' },
  TD: { pt: 'Chade', en: 'Chad' },
  CL: { pt: 'Chile', en: 'Chile' },
  CN: { pt: 'China', en: 'China' },
  CO: { pt: 'Colômbia', en: 'Colombia' },
  KM: { pt: 'Comores', en: 'Comoros' },
  CG: { pt: 'Congo', en: 'Republic of the Congo' },
  CD: { pt: 'República Democrática do Congo', en: 'Democratic Republic of the Congo' },
  CR: { pt: 'Costa Rica', en: 'Costa Rica' },
  CI: { pt: 'Costa do Marfim', en: 'Ivory Coast' },
  HR: { pt: 'Croácia', en: 'Croatia' },
  CU: { pt: 'Cuba', en: 'Cuba' },
  CY: { pt: 'Chipre', en: 'Cyprus' },
  CZ: { pt: 'Tchéquia', en: 'Czech Republic' },
  DK: { pt: 'Dinamarca', en: 'Denmark' },
  DJ: { pt: 'Djibuti', en: 'Djibouti' },
  DM: { pt: 'Dominica', en: 'Dominica' },
  DO: { pt: 'República Dominicana', en: 'Dominican Republic' },
  EC: { pt: 'Equador', en: 'Ecuador' },
  EG: { pt: 'Egito', en: 'Egypt' },
  SV: { pt: 'El Salvador', en: 'El Salvador' },
  GQ: { pt: 'Guiné Equatorial', en: 'Equatorial Guinea' },
  ER: { pt: 'Eritreia', en: 'Eritrea' },
  EE: { pt: 'Estônia', en: 'Estonia' },
  SZ: { pt: 'Essuatíni', en: 'Eswatini' },
  ET: { pt: 'Etiópia', en: 'Ethiopia' },
  FJ: { pt: 'Fiji', en: 'Fiji' },
  FI: { pt: 'Finlândia', en: 'Finland' },
  FR: { pt: 'França', en: 'France' },
  GA: { pt: 'Gabão', en: 'Gabon' },
  GM: { pt: 'Gâmbia', en: 'Gambia' },
  GE: { pt: 'Geórgia', en: 'Georgia' },
  DE: { pt: 'Alemanha', en: 'Germany' },
  GH: { pt: 'Gana', en: 'Ghana' },
  GR: { pt: 'Grécia', en: 'Greece' },
  GD: { pt: 'Granada', en: 'Grenada' },
  GT: { pt: 'Guatemala', en: 'Guatemala' },
  GN: { pt: 'Guiné', en: 'Guinea' },
  GW: { pt: 'Guiné-Bissau', en: 'Guinea-Bissau' },
  GY: { pt: 'Guiana', en: 'Guyana' },
  HT: { pt: 'Haiti', en: 'Haiti' },
  HN: { pt: 'Honduras', en: 'Honduras' },
  HU: { pt: 'Hungria', en: 'Hungary' },
  IS: { pt: 'Islândia', en: 'Iceland' },
  IN: { pt: 'Índia', en: 'India' },
  ID: { pt: 'Indonésia', en: 'Indonesia' },
  IR: { pt: 'Irã', en: 'Iran' },
  IQ: { pt: 'Iraque', en: 'Iraq' },
  IE: { pt: 'Irlanda', en: 'Ireland' },
  IL: { pt: 'Israel', en: 'Israel' },
  IT: { pt: 'Itália', en: 'Italy' },
  JM: { pt: 'Jamaica', en: 'Jamaica' },
  JP: { pt: 'Japão', en: 'Japan' },
  JO: { pt: 'Jordânia', en: 'Jordan' },
  KZ: { pt: 'Cazaquistão', en: 'Kazakhstan' },
  KE: { pt: 'Quênia', en: 'Kenya' },
  KI: { pt: 'Kiribati', en: 'Kiribati' },
  KP: { pt: 'Coreia do Norte', en: 'North Korea' },
  KR: { pt: 'Coreia do Sul', en: 'South Korea' },
  KW: { pt: 'Kuweit', en: 'Kuwait' },
  KG: { pt: 'Quirguistão', en: 'Kyrgyzstan' },
  LA: { pt: 'Laos', en: 'Laos' },
  LV: { pt: 'Letônia', en: 'Latvia' },
  LB: { pt: 'Líbano', en: 'Lebanon' },
  LS: { pt: 'Lesoto', en: 'Lesotho' },
  LR: { pt: 'Libéria', en: 'Liberia' },
  LY: { pt: 'Líbia', en: 'Libya' },
  LI: { pt: 'Liechtenstein', en: 'Liechtenstein' },
  LT: { pt: 'Lituânia', en: 'Lithuania' },
  LU: { pt: 'Luxemburgo', en: 'Luxembourg' },
  MG: { pt: 'Madagascar', en: 'Madagascar' },
  MW: { pt: 'Malauí', en: 'Malawi' },
  MY: { pt: 'Malásia', en: 'Malaysia' },
  MV: { pt: 'Maldivas', en: 'Maldives' },
  ML: { pt: 'Mali', en: 'Mali' },
  MT: { pt: 'Malta', en: 'Malta' },
  MH: { pt: 'Ilhas Marshall', en: 'Marshall Islands' },
  MR: { pt: 'Mauritânia', en: 'Mauritania' },
  MU: { pt: 'Maurício', en: 'Mauritius' },
  MX: { pt: 'México', en: 'Mexico' },
  FM: { pt: 'Micronésia', en: 'Micronesia' },
  MD: { pt: 'Moldávia', en: 'Moldova' },
  MC: { pt: 'Mônaco', en: 'Monaco' },
  MN: { pt: 'Mongólia', en: 'Mongolia' },
  ME: { pt: 'Montenegro', en: 'Montenegro' },
  MA: { pt: 'Marrocos', en: 'Morocco' },
  MZ: { pt: 'Moçambique', en: 'Mozambique' },
  MM: { pt: 'Mianmar', en: 'Myanmar' },
  NA: { pt: 'Namíbia', en: 'Namibia' },
  NR: { pt: 'Nauru', en: 'Nauru' },
  NP: { pt: 'Nepal', en: 'Nepal' },
  NL: { pt: 'Países Baixos', en: 'Netherlands' },
  NZ: { pt: 'Nova Zelândia', en: 'New Zealand' },
  NI: { pt: 'Nicarágua', en: 'Nicaragua' },
  NE: { pt: 'Níger', en: 'Niger' },
  NG: { pt: 'Nigéria', en: 'Nigeria' },
  MK: { pt: 'Macedônia do Norte', en: 'North Macedonia' },
  NO: { pt: 'Noruega', en: 'Norway' },
  OM: { pt: 'Omã', en: 'Oman' },
  PK: { pt: 'Paquistão', en: 'Pakistan' },
  PW: { pt: 'Palau', en: 'Palau' },
  PA: { pt: 'Panamá', en: 'Panama' },
  PG: { pt: 'Papua-Nova Guiné', en: 'Papua New Guinea' },
  PY: { pt: 'Paraguai', en: 'Paraguay' },
  PE: { pt: 'Peru', en: 'Peru' },
  PH: { pt: 'Filipinas', en: 'Philippines' },
  PL: { pt: 'Polônia', en: 'Poland' },
  PT: { pt: 'Portugal', en: 'Portugal' },
  QA: { pt: 'Catar', en: 'Qatar' },
  RO: { pt: 'Romênia', en: 'Romania' },
  RU: { pt: 'Rússia', en: 'Russia' },
  RW: { pt: 'Ruanda', en: 'Rwanda' },
  KN: { pt: 'São Cristóvão e Nevis', en: 'Saint Kitts and Nevis' },
  LC: { pt: 'Santa Lúcia', en: 'Saint Lucia' },
  VC: { pt: 'São Vicente e Granadinas', en: 'Saint Vincent and the Grenadines' },
  WS: { pt: 'Samoa', en: 'Samoa' },
  SM: { pt: 'San Marino', en: 'San Marino' },
  ST: { pt: 'São Tomé e Príncipe', en: 'Sao Tome and Principe' },
  SA: { pt: 'Arábia Saudita', en: 'Saudi Arabia' },
  SN: { pt: 'Senegal', en: 'Senegal' },
  RS: { pt: 'Sérvia', en: 'Serbia' },
  SC: { pt: 'Seicheles', en: 'Seychelles' },
  SL: { pt: 'Serra Leoa', en: 'Sierra Leone' },
  SG: { pt: 'Singapura', en: 'Singapore' },
  SK: { pt: 'Eslováquia', en: 'Slovakia' },
  SI: { pt: 'Eslovênia', en: 'Slovenia' },
  SB: { pt: 'Ilhas Salomão', en: 'Solomon Islands' },
  SO: { pt: 'Somália', en: 'Somalia' },
  ZA: { pt: 'África do Sul', en: 'South Africa' },
  SS: { pt: 'Sudão do Sul', en: 'South Sudan' },
  ES: { pt: 'Espanha', en: 'Spain' },
  LK: { pt: 'Sri Lanka', en: 'Sri Lanka' },
  SD: { pt: 'Sudão', en: 'Sudan' },
  SR: { pt: 'Suriname', en: 'Suriname' },
  SE: { pt: 'Suécia', en: 'Sweden' },
  CH: { pt: 'Suíça', en: 'Switzerland' },
  SY: { pt: 'Síria', en: 'Syria' },
  TJ: { pt: 'Tajiquistão', en: 'Tajikistan' },
  TZ: { pt: 'Tanzânia', en: 'Tanzania' },
  TH: { pt: 'Tailândia', en: 'Thailand' },
  TL: { pt: 'Timor-Leste', en: 'Timor-Leste' },
  TG: { pt: 'Togo', en: 'Togo' },
  TO: { pt: 'Tonga', en: 'Tonga' },
  TT: { pt: 'Trinidad e Tobago', en: 'Trinidad and Tobago' },
  TN: { pt: 'Tunísia', en: 'Tunisia' },
  TR: { pt: 'Turquia', en: 'Turkey' },
  TM: { pt: 'Turcomenistão', en: 'Turkmenistan' },
  TV: { pt: 'Tuvalu', en: 'Tuvalu' },
  UG: { pt: 'Uganda', en: 'Uganda' },
  UA: { pt: 'Ucrânia', en: 'Ukraine' },
  AE: { pt: 'Emirados Árabes Unidos', en: 'United Arab Emirates' },
  GB: { pt: 'Reino Unido', en: 'United Kingdom' },
  US: { pt: 'Estados Unidos', en: 'United States' },
  UY: { pt: 'Uruguai', en: 'Uruguay' },
  UZ: { pt: 'Uzbequistão', en: 'Uzbekistan' },
  VU: { pt: 'Vanuatu', en: 'Vanuatu' },
  VA: { pt: 'Vaticano', en: 'Vatican City' },
  VE: { pt: 'Venezuela', en: 'Venezuela' },
  VN: { pt: 'Vietnã', en: 'Vietnam' },
  YE: { pt: 'Iêmen', en: 'Yemen' },
  ZM: { pt: 'Zâmbia', en: 'Zambia' },
  ZW: { pt: 'Zimbábue', en: 'Zimbabwe' },
  PS: { pt: 'Palestina', en: 'Palestine' },
  TW: { pt: 'Taiwan', en: 'Taiwan' },
  HK: { pt: 'Hong Kong', en: 'Hong Kong' },
  MO: { pt: 'Macau', en: 'Macau' }
};

export const COUNTRIES = Object.entries(COUNTRY_NAMES).map(([code, names]) => ({
  code,
  name: names.pt,
  nameEn: names.en,
  flag: getFlag(code)
}));

function getFlag(code) {
  if (!code || code.length !== 2) return '🏳️';
  return String.fromCodePoint(...code.toUpperCase().split('').map((c) => 127397 + c.charCodeAt(0)));
}

export function getCountryName(code, lang = 'pt') {
  if (!code || code === 'any') return lang === 'en' ? 'Any Country' : 'Qualquer País';
  const found = COUNTRIES.find(c => c.code.toUpperCase() === String(code).toUpperCase());
  if (!found) return code;
  if (lang === 'en') return found.nameEn || found.name;
  return found.name;
}
